### PR TITLE
Add docker build script 

### PR DESCRIPTION
**Pull request by karel-3d**
I have added emulator build to docker.

Note that it requires changes from https://github.com/trezor/trezor-mcu/pull/301 

The readme mentions env variable from this PR https://github.com/trezor/trezor-mcu/pull/302

### CODE REVIEW

**Comment by prusnak** [comment]
TBH I don't really like the change. If you really want to have this I suggest creating `Dockerfile.emulator` with the new contents and update `build-emulator.sh` to use that file (just update `IMAGE` variable to `trezor-mcu-build-emulator` or sth similar and add `-f Dockerfile.emulator` to the `docker build` call in `build-emulator.sh`).

**Comment by karel-3d** [comment]
Good idea

**Comment by karel-3d** [comment]
Is this better?

**Comment by prusnak** [comment]
Much better ❤️

**Comment by karel-3d** [comment]
It seems I am building libopencm3 which is not needed. And I install ARM packages that are not necessary. Should I make a separate PR for that?

**Comment by prusnak** [comment]
Yes, please.

**Pull request merged**
