### PR TITLE
Added bootloader autobuild with docker

### PR DESCRIPTION
**Pull request by karek314**
Added bootloader autobuild with docker and bootloader.bin size check

### CODE REVIEW

**Comment by karek314** [comment]
32000 bytes means max allowed bootloader size in case this mcu to work correctly.

**Comment by prusnak** [comment]
It is 32768 actually.

**Comment by karek314** [comment]
Actually it doesn't matter much since depending on settings in Makefile, bootloader was usually way above 32kb. But i have corrected. It may be useful when compiling bootloader first time.

**Comment by prusnak** [comment]
Rebased commits into one da027f7652dd25ff7071562b57f3dd9a9349db72 and merged in. Thanks!

**Pull request closed without merging**
