### PR TITLE
Added Vertcoin VTC to coins.c

### PR DESCRIPTION
**Pull request by darrenturn90**
Added Vertcoin VTC to coins.c

### CODE REVIEW

**Comment by prusnak** [comment]
Which wallet does support TREZOR and Vertcoin at the same time?

**Comment by slush0** [comment]
Really change device manufacturer to vertcointrezor.com?

**Comment by prusnak** [comment]
ROFL

**Comment by darrenturn90** [comment]
That wasn't in the pushed code (well, it shouldn't have been), merely the
addresskey change in coins.h

**Comment by lzsaver** [comment]
https://github.com/vertcoin/trezor-mcu/commit/d26ac2ec67579762d06914cfaeca7eb7b0258446

**Pull request closed without merging**
