### PR TITLE
Second bootloader support (fastflash)

### PR DESCRIPTION
**Pull request by saleemrashid**
Add second bootloader support to enable faster flashing of firmware. This is similar to @jhoenicke's [`bootloaderhack`](https://github.com/jhoenicke/trezor-mcu/tree/bootloaderhack), but has a few advantages

* It does not affect normal builds of the firmware or the bootloader (so it can be merged into `master`)
* ~~The linker script reserves exactly the size of the bootloader~~ (not compatible with GCC 4.9.3)
* The linker script avoids use of magic constants (more avoidance is possible but it breaks compatibility with GCC 4.9.3)
* The linker verifies that the bootloader fits into the reserved space
* The bootloader does not waste time verifying the signatures (and unconditionally wipes the metadata)

### CODE REVIEW

**Comment by saleemrashid** [comment]
@prusnak PING :)

**Comment by saleemrashid** [comment]
@prusnak `PING`

**Comment by jhoenicke** [comment]
I see that you reserve 20 kB of precious RAM for the bootloader, even if it is not loaded.  It looks like we have enough memory now, but it would be good to avoid that. 

BTW, do you know a good tool to compute the maximum stack usage?  The code is non-recursive and I think doesn't use dynamic array sizes, so it should be possible to compute this automatically.

**Comment by saleemrashid** [comment]
@jhoenicke It's the safest way to do this because that linker feature is designed precisely for situations like this.

Furthermore, the likelihood of running out of RAM is miniscule (`.data` + `.bss` is 80 KiB), we're far more likely to run out of ROM (which happens with GCC 4.8.2).

**Comment by saleemrashid** [comment]
@prusnak The last two commits are optional because #178 reduces the firmware size which enables compilation with GCC 4.8.2

**Comment by prusnak** [comment]
Merged except last two commits. Thanks!

**Pull request merged**
