### PR TITLE
recovery: mark all related variables as confidential

### PR DESCRIPTION
**Pull request by romanz**
Following https://github.com/trezor/trezor-mcu/commit/98e617d8740b85ae01d7d6e0dd3f49e66057a210.

### CODE REVIEW

**Comment by prusnak** [comment]
What exactly is the line of attack you are trying to prevent?

I don't think any of the variables used during recovery are confidential.

// cc @jhoenicke any thoughts on this?

**Comment by romanz** [comment]
IIUC, after a dry-run recovery process is over, the `words`  variable (defined [here](https://github.com/trezor/trezor-mcu/pull/214/commits/9372d67804fa0bce1b15f49083cbebfed9cbc273?diff=split#diff-9c1db82f2b5e3cf122881188de852e6aR78)) contains the secret mnemonic. I thought that it also should be erased after a soft reset (by putting it into the `CONFIDENTIAL` linker section).

**Comment by prusnak** [comment]
But they contain the mnemonic user just entered, no?

**Comment by saleemrashid** [comment]
If the recovery is completed, these will be wiped from SRAM. If the recovery is not completed, we can assume that the user is present (e.g. it would far more likely they are physically attacked for the mnemonic words than the attacker extracts them from SRAM)

**Comment by saleemrashid** [comment]
Also, variables like `awaiting_word`, `dry_run` and `enforce_wordlist` are not confidential in any way (and we should ensure that `.confidential` remains as small as possible)

**Comment by romanz** [comment]
I agree with https://github.com/trezor/trezor-mcu/pull/214#issuecomment-325424089.
Closing this PR.

**Pull request closed without merging**
