### PR TITLE
Fix building firmware in docker

### LINKED ISSUE #320: Build firmware script not building on Ubuntu
On Ubuntu I could not build... get following message:
*** No rule to make target '../bootloader/bootloader.bin', needed by 'bl_data.h'. Stop.
make: Leaving directory '/trezor-mcu/firmware'

There was a commit to a Makefile: https://github.com/trezor/trezor-mcu/commit/9588e8f2736b60916f51e470deb18f55112a6ebc that might have something to do with this. Please advise. Thanks.

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**
This fixes #320

### CODE REVIEW

**Comment by yura-pakhuchiy** [comment]
However this does not fixes verifying fingerprint of officials builds, eg.:
```
$ ./build-firmware.sh v1.6.1
...
Filename    : build/trezor-v1.6.1.bin
Fingerprint : c2ba53cf5398e142c4d04d8c95538080167510532e4d47c633d052aff22b0f79
Size        : 430908 bytes (out of 491520 maximum)
```
but
```
$ wget -O trezor.signed.bin https://wallet.trezor.io/data/firmware/1/trezor-1.6.1.bin
...
$ tail -c +257 trezor.signed.bin | sha256sum
83c3190a94e524ac83a1704eb584a2ab53f8a65a893b1ab52e7135812857c807  -
```

**Comment by kevinwchang** [comment]
It appears the bootloader.bin used to build the official firmware was **not** aligned, so build-firmware.sh should only use `make -C bootloader`, not ``make -C bootloader align`. With that change, I get the right fingerprint.

**Comment by yura-pakhuchiy** [comment]
@kevinwchang Indeed, now fingerprint matches! Thank you! I have updated the patch.

**Comment by yura-pakhuchiy** [comment]
Looks like running custom firmware is broken in 1.6.1 :-(. When I flash custom build firmware with fingerprint matching official, it shows: "Hard fault detected. Please unplug device."

**Comment by prusnak** [comment]
We'll fix that in the future.

**Pull request merged**
