### PR TITLE
Optional merge: OpenPGP support

### PR DESCRIPTION
**Pull request by saleemrashid**
Adds support for making ECDSA signatures (NIST P-256) using the TREZOR as an
OpenPGP smart card.

Works completely natively on Linux and Windows, macOS is untested. `trezorctl`
is required to generate the Public Key but after that, it can be used with
GnuPG as a standard OpenPGP smart card. If using `libccid`, it may be required
to add the USB VID/PID to `/etc/libccid_Info.plist`

```bash
$ trezorctl initialize_openpgp | gpg2 --import # Import the TREZOR Public Key
$ gpg2 --card-status # Create Secret Key Stub
$ # Now the TREZOR can be used as a standard OpenPGP smart card
```

```bash
$ trezorctl load_device -m all all all all all all all all all all all all
$ trezorctl initialize_openpgp -e nist256p1 -t 0 -u "TREZOR" | gpg --import
gpg: key EDD78A88C5D03B56: public key "TREZOR" imported
gpg: Total number processed: 1
gpg:               imported: 1
$ gpg --send-keys EDD78A88C5D03B56
gpg: sending key EDD78A88C5D03B56 to hkps://hkps.pool.sks-keyservers.net
```

http://pgp.mit.edu/pks/lookup?op=vindex&search=0xEDD78A88C5D03B56
https://sks-keyservers.net/pks/lookup?op=vindex&search=0xEDD78A88C5D03B56
http://keys.gnupg.net/pks/lookup?op=vindex&search=0xEDD78A88C5D03B56

## TODO

- [x] Sub key binding signatures
- [x] Authentication support
- [ ] Decryption support
- [ ] Ed25519 support

## Points of interest

* The curve could be switched to `seck256p1` and GnuPG could be used to sign
  Bitcoin transactions! :laughing:
* Importing the Public Key is the only TREZOR-specific command
* Eventually, the TREZOR could have complete smart card support, some examples
  of the features this provides are: Windows authentication (including
  BitLocker), OpenSSH support, and more widespread use in the workplace

trezor/trezor-common#21
trezor/python-trezor#88

### CODE REVIEW

**Comment by saleemrashid** [comment]
I'm going to refactor all of the OpenPGP structures to [trezor/trezor-crypto](https://github.com/trezor/trezor-crypto) to allow testing for correctness, bad memory access and preparing for TREZOR 2

**Comment by saleemrashid** [comment]
This is an optional merge, you probably out to wait for me to refactor most of the code to [saleemrashid/trezor-ccid](https://github.com/saleemrashid/trezor-ccid) and [saleemrashid/trezor-openpgp](https://github.com/saleemrashid/trezor-openpgp)

**Comment by prusnak** [comment]
I think it would be great to have the code separated into separate modules. I still have some other stuff in the merge queue. :-/

**Comment by saleemrashid** [comment]
@prusnak Yeah, it enables me to write unit tests and integration tests. Also, I can implement PKCS#15 trivially, enabling SSH support and full OpenSC support.

**Pull request closed without merging**
