### PR TITLE
 Refactor message processing to remove tiny mode stack

### PR DESCRIPTION
**Pull request by saleemrashid**
Re-use the normal message processing stack for tiny mode.

Depends on https://github.com/saleemrashid/trezor-common/tree/wire-no-fsm

### CODE REVIEW

**Comment by prusnak** [comment]
I merged the changes into trezor-common and cherry picked e61ec5ba2d54329bc5966004e5b03a0809700cc2 (as dbb3e927eccc565bbc767fcd002d3c286fc23e5c)

I also did some major changes to reflect the nested structure of protobuf messages. If you have time, could you please rebase? Thanks!

**Comment by saleemrashid** [comment]
@prusnak Rebased. Might want to cherry-pick c7284b8ff0777ec02d5c88f71348b833981ba301.

**Comment by saleemrashid** [comment]
Never mind, rebased again and you've fixed that in `master` now

**Comment by prusnak** [comment]
Let's not add this. We are porting trezor-core to T1, which should resolve this issue.

**Pull request closed without merging**
