### PR TITLE
Add Fujicoin

### PR DESCRIPTION
**Pull request by fujicoin**
Hi  prusnak,

Please add Fujicoin.

We are now developing electrum-FJC.
The electrum-FJC for test can be obtained here.
https://bitcointalk.org/index.php?topic=644601.msg20043948#msg20043948

Website: http://www.fujicoin.org/
Explorer: http://explorer.fujicoin.org/
electrum-FJC: https://github.com/fujicoin/electrum-fjc

Thanks,
motty

### CODE REVIEW

**Comment by prusnak** [comment]
There is no need to always open new pull request. Just push or force-push into your branch and the pull request will be updated.

**Comment by fujicoin** [comment]
Hi prusnak,

Thanks!

motty

**Comment by prusnak** [comment]
Please send a pull request to trezor-common, where you would add your coin to coins.json: https://github.com/trezor/trezor-common/blob/master/coins.json

**Comment by fujicoin** [comment]
Hi prusnak,

Thank you.
I have created a new pull request.

Best regards,
motty

**Pull request closed without merging**
