### PR TITLE
Refactor code generation

### LINKED ISSUE #281: Failure in nem_mosaics.py doesn't terminate make

### PR DESCRIPTION
**Pull request by saleemrashid**
* Add `GENERATE_CODE` function to `Makefile` (fixes #281)
* Refactor `coins-gen.py` to `coin_info.py` (based on `nem_mosaics.py`)
* Do not run the device tests on Travis CI if the build fails.

`coin_info.py` is more robust than `coins-gen.py` because we use named members in the structure. This prevents subtle bugs where compilation succeeds but the members in `coins-gen.py` do not match up with `CoinInfo`. The resulting `coin_info.c` is more verbose but far easier to read.

/cc @jpz

### CODE REVIEW

**Comment by jpz** [comment]
Tidy work - very readable. 👍

**Comment by saleemrashid** [comment]
Rebased on `master` and fixes a linker issue introduced in be64864efc8399572b2b665705258b663d1d0363.

@jhoenicke Was there any particular reason to remove the `__stack_chk_guard` definition?

**Comment by prusnak** [comment]
I think you did not want to commit firmware/coins_array.h and firmware/coins_count.h in 8268e8e3567ae9e3f2395d61fb5625d32e60ca51

Otherwise LGTM

**Comment by saleemrashid** [comment]
Fixed

**Comment by prusnak** [comment]
Thanks!

**Pull request merged**
