### PR TITLE
Pack layout if lines too long

### PR DESCRIPTION
**Pull request by karel-3d**
This actually fixes https://github.com/trezor/trezor-mcu/issues/289

Note that with this fix, https://github.com/trezor/trezor-mcu/commit/f70772fb58126cdca155d2d5a335c605c47b93a6 is no longer needed

### CODE REVIEW

**Comment by jhoenicke** [comment]
The test for > 21 is quite optimistic.  It sometimes runs out of the display already with 19 characters.

One problem is still the variable font size.  If the addresses contain too many Ms and Ws they extend outside the display.  I wonder if we should include a fixed size font, where every letter has a width of 5+1 pixels.  This would make it more predictable whether an address always fits.

BTW, bitcoincash addresses are 54 characters long (at least the ones that currently have a meaning) including the "bitcoincash:" prefix, which is part of the address, but doesn't really have to be checked by the user.  Bech32 addresses are 44 characters for simple addresses and 64 for multisig/htlc (assuming no more than 4 character prefix).  So multisig bech32 addresses are currently the bottleneck.

**Comment by saleemrashid** [comment]
Related: #286 which would include wrapping on text width, not length.

**Comment by karel-3d** [comment]
Width of string can be computed via `fontCharWidth`, right?

**Comment by prusnak** [comment]
> I wonder if we should include a fixed size font, where every letter has a width of 5+1 pixels. This would make it more predictable whether an address always fits.

I like this. Originally, we had a non-proportional font of exactly this size, but we decided to use the proportional font for addresses too as it had better results (more letters per line) in overall.

With 6 pixels per character we can fit 21 letters per line. With 3 lines per address we can have at most 63 characters, so we are still missing one character for Bech32 multisig! :-/

**Comment by mariodian** [comment]
How about the font size would get smaller as the text can no longer fit on the screen? A Bech32 multisig address is off the screen by a single character so in order to fit it in, the font size wouldn't even be so drastically smaller (just 4+1 instead of 5+1).

Have a look at [this example](http://jquery-textfill.github.io). Apple has been using it on iPhones for ages so I'd say people are even used to it. 

Another solution could be just to have 3 dots in the middle of the address. 

`bc1pw508d6qejxtdg4y5r3zarvary0c5...kw508d6qejxtdg4y5r3zarvary0c5xw7k7grplx`

It doesn't necessarily have to cause any issues since it's safe to assume people only check the beginning and the end of the address to see whether it's correct.

**Comment by prusnak** [comment]
Obsoleted by https://github.com/trezor/trezor-mcu/pull/295

**Pull request closed without merging**
