### PR TITLE
WIP: Add support for multi-byte address prefixes and update Zcash prefixes

### PR DESCRIPTION
**Pull request by daira**
Also add support for the Zcash testnet. refs #117

### CODE REVIEW

**Comment by daira** [comment]
github seems to be confused about the order of commits; 3942dc1 is last (but they commute so it doesn't matter much).

**Comment by prusnak** [comment]
Merged in https://github.com/trezor/trezor-mcu/commit/6bfe487f19aa1b6407fb876d6cd8e7d786fbd759

Thanks!

PS: Also added one commit that simplifies cryptoMessageVerify: https://github.com/trezor/trezor-mcu/commit/3a42032c63ab4c8d2bd1769b25bcc502934376e0

**Comment by daira** [comment]
Excellent, thankyou!

**Comment by daira** [comment]
I made some comments on https://github.com/trezor/trezor-mcu/commit/69d99d202d0d9360c6cdbef9e17f25cd81477ff1 and https://github.com/trezor/trezor-mcu/commit/3a42032c63ab4c8d2bd1769b25bcc502934376e0

**Comment by prusnak** [comment]
I run the unit tests on the device from here: https://github.com/trezor/python-trezor/tree/master/tests

and they went OK, so the good thing is that we did not break existing things.

Do you have time to add more test cases (for ZCash, so multibyte stuff gets triggered) for affected calls? (such as `signmessage`, `verifymessage`, `signtx`).

**Comment by daira** [comment]
I will probably get some time to work on this on Friday; not before.

**Pull request closed without merging**
