### PR TITLE
add Mazacoin support

### PR DESCRIPTION
**Pull request by Kefkius**
Add support for Mazacoin blockchain

### CODE REVIEW

**Comment by prusnak** [comment]
Is there a working BIP-0044 implementation Wallet for Mazacoin?

**Comment by Kefkius** [comment]
@prusnak Yes, our multi-coin Electrum fork Encompass https://github.com/mazaclub/encompass. It's completely BIP-0044 compatible and has Mazacoin support.

**Comment by prusnak** [comment]
We wont add this coin for the time being. It's capitalization is too smart for the time being and we don't like to pollute the codebase with unused coins.

**Comment by ELM4Ever** [comment]
Please reconsider including MZC: the development team behind MZC are the creators of Encompass - the first multi-coins SPV.  Our company is currently developing an exchange solution, with peer-to-peer settlement, which will use Encompass and Trezor as the main components of the overall security model.  We have mandated Encompass to be the first SPV wallet to incorporate support the multisig function on Trezor, for all their supported coins (which also includes MZC).   Please contact me directly for further details.

**Pull request closed without merging**
