### PR TITLE
Clean-up of oled code.

### PR DESCRIPTION
**Pull request by jhoenicke**
Get rid of the macros to access pixels.  Use only the functions instead.
Simplified some of the drawing functions.

### CODE REVIEW

**Comment by saleemrashid** [comment]
I think there should be  `OLED_INDEX` and `OLED_MASK` macros to remove repetition of the same indexing and masking.

**Comment by jhoenicke** [comment]
Forced push with the macros.  Code produced is the same.

**Comment by saleemrashid** [comment]
I think you should remove `x` from `OLED_MASK(x, y)`

**Comment by saleemrashid** [comment]
Also, would it be a good idea to make the arguments `unsigned` or even `uint8_t`?

**Comment by jhoenicke** [comment]
OLED_MASK: it's intentional, otherwise you may accidently give x instead of y.
unsigned:  Most operations should cleanly handle out of screen access, e.g. draw centered string may run to the left and right outside the screen in exceptional cases (e.g. when signing MMMMMMMMMMMMMMM).

**Comment by saleemrashid** [comment]
@jhoenicke Makes sense

**Comment by prusnak** [comment]
Thanks!

**Pull request merged**
