### PR TITLE
Update README.md with working instructions

### PR DESCRIPTION
**Pull request by nezza**

### CODE REVIEW

**Comment by prusnak** [comment]
Fix typo in the word `recursive`

**Comment by nezza** [comment]
Cloning recursively does fix the build, though if this solution also works please use what ever you prefer.

**Comment by prusnak** [comment]
Fixed in 06fbb91f128fbb45bd3527463d0ad21838db8ca5

**Comment by saleemrashid** [comment]
@nezza If you're building in the repository, sure. But the instructions in the `README` will fire off a Docker build that might then checkout different revisions of the repository (and the sub-submodules might end up out of sync, which would cause issues).

**Comment by nezza** [comment]
@saleemrashid Unfortunately this still does not work:

```
git clone https://github.com/trezor/trezor-mcu.git 
cd trezor-mcu
./build.sh 06fbb91f128fbb45bd3527463d0ad21838db8ca5 06fbb91f128fbb45bd3527463d0ad21838db8ca5
```

```
...
HEAD is now at 06fbb91... build: added --recursive to git clone in Makefile and script/bootstrap
Submodule 'libopencm3' (https://github.com/libopencm3/libopencm3.git) registered for path 'vendor/libopencm3'
Submodule 'vendor/nanopb' (https://github.com/nanopb/nanopb.git) registered for path 'vendor/nanopb'
Submodule 'trezor-common' (https://github.com/trezor/trezor-common.git) registered for path 'vendor/trezor-common'
Submodule 'trezor-crypto' (https://github.com/trezor/trezor-crypto.git) registered for path 'vendor/trezor-crypto'
Submodule 'trezor-qrenc' (https://github.com/trezor/trezor-qrenc.git) registered for path 'vendor/trezor-qrenc'
fatal: submodule 'libopencm3' cannot add alternate: path '/src/.git/modules/libopencm3/' does not exist
Failed to clone 'vendor/libopencm3'. Retry scheduled
fatal: submodule 'vendor/nanopb' cannot add alternate: path '/src/.git/modules/vendor/nanopb/' does not exist
Failed to clone 'vendor/nanopb'. Retry scheduled
fatal: submodule 'trezor-common' cannot add alternate: path '/src/.git/modules/trezor-common/' does not exist
Failed to clone 'vendor/trezor-common'. Retry scheduled
fatal: submodule 'trezor-crypto' cannot add alternate: path '/src/.git/modules/trezor-crypto/' does not exist
Failed to clone 'vendor/trezor-crypto'. Retry scheduled
fatal: submodule 'trezor-qrenc' cannot add alternate: path '/src/.git/modules/trezor-qrenc/' does not exist
Failed to clone 'vendor/trezor-qrenc'. Retry scheduled
fatal: submodule 'libopencm3' cannot add alternate: path '/src/.git/modules/libopencm3/' does not exist
Failed to clone 'vendor/libopencm3' a second time, aborting
```

With a recursive clone it works.

**Comment by nezza** [comment]
Thanks, that fixed it :)

**Pull request closed without merging**
